name: flut_cinematic
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dio: ^5.4.0
  firebase_core: ^2.25.4
  flut_cinematic_api_client:
    path: packages/flut_cinematic_api_client
  flut_cinematic_common:
    path: packages/flut_cinematic_common
  flut_cinematic_data:
    path: packages/flut_cinematic_data  
  flut_cinematic_domain:
    path: packages/flut_cinematic_domain
  flut_cinematic_firebase:
    path: packages/flut_cinematic_firebase  
  flut_cinematic_ui:
    path: packages/flut_cinematic_ui 
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  hooks_riverpod: ^2.4.9
  intl: ^0.18.1
  qr_flutter: ^4.1.0
  riverpod: ^2.4.9
  slang: ^3.28.0
  slang_flutter: ^3.28.0
  url_launcher: ^6.2.4

dev_dependencies:
  build_runner: ^2.4.8     
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  slang_build_runner: ^3.28.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
